### ISSUE TITLE
Нолик не может выиграть

### ISSUE THREAD

**Issue by zelenyhleb** [AParovyshnaya/Noughts-Crosses#19]
![изображение](https://user-images.githubusercontent.com/15957500/128985250-6b4ca60b-f48b-4ec8-b922-2f78e984ff17.png)

Такое состояние поля не определяется как выигрыш нолика, хотя его выигрыш очевиден (три нолика по диагонали)

**Comment by AParovyshnaya** [comment]
Сейчас диагонали буду переделывать (#17 ). По рядам побеждают нолики.

**Comment by zelenyhleb** [comment]
![изображение](https://user-images.githubusercontent.com/15957500/128993746-00931089-8189-48ca-bd6c-41283cd4cb5d.png)
Ни крестики, ни нолики не побеждают по диагонали на бесконечном поле

**Comment by AParovyshnaya** [comment]
Смотри в #17. Я там буду переделывать диагонали.

**Comment by AParovyshnaya** [comment]
Я переделала, вроде всё работает.
