### ISSUE TITLE
Адаптация под мобильные устройства

### ISSUE THREAD

**Issue by zelenyhleb** [AParovyshnaya/Noughts-Crosses#22]
Иногда бывает так, что поиграть в Noughts-crosses хочется прямо в дороге, когда нет доступа к компьютеру. В таких случаях логично воспользоваться мобильным устройством, однако UX на телефонах оставляет желать лучшего:
<img src="https://user-images.githubusercontent.com/15957500/129895736-8e540e4d-6aa1-4c0d-9cbf-b9ea153bbe14.png" width="400"/>

Элементы управления (в том числе поле) очень маленькие, по ним тяжело попасть, а большая часть экрана не используется игрой вовсе.

Было бы классно иметь адаптированную под мобильные устройства версию: сперва хотя бы просто по кнопке где-нибудь в углу, а позже, конечно, было бы очень хорошо, если бы сайт сам умел распознавать, с мобильного или настольного устройства он запущен, и соответственно выбирать мобильную либо настольную версию.

**Comment by AParovyshnaya** [comment]
Осталось немного - сделать поле 19х19 удобнее (в крайние клетки не попасть).

**Comment by AParovyshnaya** [comment]
Вообще ничего не влилось в main!

**Comment by AParovyshnaya** [comment]
Оказалось, что влилось, но при запуске через ссылку из README в index-е нет изменений

**Comment by AParovyshnaya** [comment]
только что нажала на ссылку, стало работать. Видимо, github-у нужно время

**Comment by AParovyshnaya** [comment]
Ура!
