### ISSUE TITLE
Клетки при нажатии съежают :(

### ISSUE THREAD

**Issue by AParovyshnaya** [AParovyshnaya/Noughts-Crosses#8]
![изображение](https://user-images.githubusercontent.com/66070466/125313002-7c214f00-e33d-11eb-8bb1-78f71e975014.png)

**Comment by AParovyshnaya** [comment]
Скорее всего, на это повлияло:
```
.line {
    margin-bottom: -26px;
}
```
Или тот факт, что внутри них svg.

Очень странным мне кажется обстоятельство:

![изображение](https://user-images.githubusercontent.com/66070466/125314500-e7b7ec00-e33e-11eb-9aed-5664103a87a5.png)

**Comment by AParovyshnaya** [comment]
Буду рада помощи @eparovyshnaya или @zelenyhleb. Но сначало, конечно, приходи @AParovyshnaya.

**Comment by zelenyhleb** [comment]
> 
> 
> Скорее всего, на это повлияло:
> 
> ```
> .line {
>     margin-bottom: -26px;
> }
> ```
> 
> Или тот факт, что внутри них svg.
> 
> Очень странным мне кажется обстоятельство:
> 
> ![изображение](https://user-images.githubusercontent.com/66070466/125314500-e7b7ec00-e33e-11eb-9aed-5664103a87a5.png)

Нет ничего странного в данном обстоятельстве. Если ты сложишь border-width+width+border-width, то аккуратно получишь свои 79 px

**Comment by AParovyshnaya** [comment]
Thank you, @zelenyhleb
